services:
  - type: web
    name: rootaiv2
    runtime: python
    region: frankfurt   # 🔥 Change si tu veux (frankfurt / oregon / etc)

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt --no-cache-dir

    startCommand: |
      python app.py

    envVars:
      - key: PORT
        value: 10000

      - key: SERPAPI_KEY
        sync: false

      - key: IMGBB_KEY
        sync: false

      - key: OPENAI_API_KEY
        sync: false

    autoDeploy: true
