services:
  - type: web
    name: rootaiv2
    env: python
    region: oregon   # ou change selon ta région
    plan: free

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: SERPAPI_KEY
        sync: false
      - key: IMGBB_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

    autoDeploy: true
